name: Release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release Tag Name
        required: true
jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install minimal nightly
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Release build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Crates Login
        run: cargo login ${{ secrets.CRATES_TOKEN }}
      - name: Release build
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --dry-run